version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./apps/api/.env.development

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/ui/.env
    depends_on:
      - api

  log-server:
    build:
      context: ./apps/log-server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./apps/log-server/.env.development

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
