/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiKeyWithEnvDto,
} from '../models/index';
import {
    ApiKeyWithEnvDtoFromJSON,
    ApiKeyWithEnvDtoToJSON,
} from '../models/index';

export interface ApiKeyControllerRevealOneRequest {
    apiKeyId: string;
}

export interface ApiKeyControllerRotateOneRequest {
    apiKeyId: string;
}

/**
 * 
 */
export class ApiKeyApi extends runtime.BaseAPI {

    /**
     */
    async apiKeyControllerGetApiKeysForProjectRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiKeyWithEnvDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiKeyWithEnvDtoFromJSON));
    }

    /**
     */
    async apiKeyControllerGetApiKeysForProject(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiKeyWithEnvDto>> {
        const response = await this.apiKeyControllerGetApiKeysForProjectRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiKeyControllerRevealOneRaw(requestParameters: ApiKeyControllerRevealOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyWithEnvDto>> {
        if (requestParameters.apiKeyId === null || requestParameters.apiKeyId === undefined) {
            throw new runtime.RequiredError('apiKeyId','Required parameter requestParameters.apiKeyId was null or undefined when calling apiKeyControllerRevealOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys/{apiKeyId}`.replace(`{${"apiKeyId"}}`, encodeURIComponent(String(requestParameters.apiKeyId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyWithEnvDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiKeyControllerRevealOne(requestParameters: ApiKeyControllerRevealOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyWithEnvDto> {
        const response = await this.apiKeyControllerRevealOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiKeyControllerRotateOneRaw(requestParameters: ApiKeyControllerRotateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyWithEnvDto>> {
        if (requestParameters.apiKeyId === null || requestParameters.apiKeyId === undefined) {
            throw new runtime.RequiredError('apiKeyId','Required parameter requestParameters.apiKeyId was null or undefined when calling apiKeyControllerRotateOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys/{apiKeyId}`.replace(`{${"apiKeyId"}}`, encodeURIComponent(String(requestParameters.apiKeyId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyWithEnvDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiKeyControllerRotateOne(requestParameters: ApiKeyControllerRotateOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyWithEnvDto> {
        const response = await this.apiKeyControllerRotateOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
