# fly.toml app configuration file generated for montelo-log-server on 2024-02-19T21:30:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'montelo-log-server'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
