/* tslint:disable */

/* eslint-disable */

/**
 * Montelo API SDK
 * This server handles creating traces and traces.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateRunInput
 */
export interface CreateRunInput {
  /**
   *
   * @type {string}
   * @memberof CreateRunInput
   */
  experimentId: string;
  /**
   *
   * @type {object}
   * @memberof CreateRunInput
   */
  input: object;
  /**
   *
   * @type {object}
   * @memberof CreateRunInput
   */
  output: object;
}

/**
 * Check if a given object implements the CreateRunInput interface.
 */
export function instanceOfCreateRunInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "experimentId" in value;
  isInstance = isInstance && "input" in value;
  isInstance = isInstance && "output" in value;

  return isInstance;
}

export function CreateRunInputFromJSON(json: any): CreateRunInput {
  return CreateRunInputFromJSONTyped(json, false);
}

export function CreateRunInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRunInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    experimentId: json["experimentId"],
    input: json["input"],
    output: json["output"],
  };
}

export function CreateRunInputToJSON(value?: CreateRunInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    experimentId: value.experimentId,
    input: value.input,
    output: value.output,
  };
}
