/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and logs.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndLogInput
 */
export interface EndLogInput {
    /**
     * 
     * @type {object}
     * @memberof EndLogInput
     */
    output?: object;
    /**
     * 
     * @type {string}
     * @memberof EndLogInput
     */
    endTime?: string;
    /**
     * 
     * @type {object}
     * @memberof EndLogInput
     */
    extra?: object;
}

/**
 * Check if a given object implements the EndLogInput interface.
 */
export function instanceOfEndLogInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EndLogInputFromJSON(json: any): EndLogInput {
    return EndLogInputFromJSONTyped(json, false);
}

export function EndLogInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndLogInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'output': !exists(json, 'output') ? undefined : json['output'],
        'endTime': !exists(json, 'endTime') ? undefined : json['endTime'],
        'extra': !exists(json, 'extra') ? undefined : json['extra'],
    };
}

export function EndLogInputToJSON(value?: EndLogInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'output': value.output,
        'endTime': value.endTime,
        'extra': value.extra,
    };
}

