/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and traces.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventQueuedDto
 */
export interface EventQueuedDto {
    /**
     * 
     * @type {boolean}
     * @memberof EventQueuedDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the EventQueuedDto interface.
 */
export function instanceOfEventQueuedDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function EventQueuedDtoFromJSON(json: any): EventQueuedDto {
    return EventQueuedDtoFromJSONTyped(json, false);
}

export function EventQueuedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventQueuedDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function EventQueuedDtoToJSON(value?: EventQueuedDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

