/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and traces.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentDto
 */
export interface ExperimentDto {
    /**
     * 
     * @type {string}
     * @memberof ExperimentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentDto
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentDto
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperimentDto
     */
    description: string | null;
}

/**
 * Check if a given object implements the ExperimentDto interface.
 */
export function instanceOfExperimentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "datasetId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function ExperimentDtoFromJSON(json: any): ExperimentDto {
    return ExperimentDtoFromJSONTyped(json, false);
}

export function ExperimentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'datasetId': json['datasetId'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function ExperimentDtoToJSON(value?: ExperimentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'datasetId': value.datasetId,
        'name': value.name,
        'description': value.description,
    };
}

