/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and logs.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FullDatasetDto } from './FullDatasetDto';
import {
    FullDatasetDtoFromJSON,
    FullDatasetDtoFromJSONTyped,
    FullDatasetDtoToJSON,
} from './FullDatasetDto';

/**
 * 
 * @export
 * @interface ExperimentWithDatapointsDto
 */
export interface ExperimentWithDatapointsDto {
    /**
     * 
     * @type {string}
     * @memberof ExperimentWithDatapointsDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentWithDatapointsDto
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentWithDatapointsDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentWithDatapointsDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentWithDatapointsDto
     */
    createdAt: string;
    /**
     * 
     * @type {FullDatasetDto}
     * @memberof ExperimentWithDatapointsDto
     */
    dataset: FullDatasetDto;
}

/**
 * Check if a given object implements the ExperimentWithDatapointsDto interface.
 */
export function instanceOfExperimentWithDatapointsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "datasetId" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "dataset" in value;

    return isInstance;
}

export function ExperimentWithDatapointsDtoFromJSON(json: any): ExperimentWithDatapointsDto {
    return ExperimentWithDatapointsDtoFromJSONTyped(json, false);
}

export function ExperimentWithDatapointsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentWithDatapointsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'datasetId': json['datasetId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': json['createdAt'],
        'dataset': FullDatasetDtoFromJSON(json['dataset']),
    };
}

export function ExperimentWithDatapointsDtoToJSON(value?: ExperimentWithDatapointsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'datasetId': value.datasetId,
        'name': value.name,
        'description': value.description,
        'createdAt': value.createdAt,
        'dataset': FullDatasetDtoToJSON(value.dataset),
    };
}

