/* tslint:disable */

/* eslint-disable */

/**
 * Montelo API SDK
 * This server handles creating traces and traces.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";
import type { FullDatasetDto } from "./FullDatasetDto";
import { FullDatasetDtoFromJSON, FullDatasetDtoFromJSONTyped, FullDatasetDtoToJSON } from "./FullDatasetDto";

/**
 *
 * @export
 * @interface FullExperimentDto
 */
export interface FullExperimentDto {
  /**
   *
   * @type {string}
   * @memberof FullExperimentDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FullExperimentDto
   */
  datasetId: string;
  /**
   *
   * @type {string}
   * @memberof FullExperimentDto
   */
  name: string | null;
  /**
   *
   * @type {string}
   * @memberof FullExperimentDto
   */
  description: string | null;
  /**
   *
   * @type {FullDatasetDto}
   * @memberof FullExperimentDto
   */
  dataset: FullDatasetDto;
}

/**
 * Check if a given object implements the FullExperimentDto interface.
 */
export function instanceOfFullExperimentDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "datasetId" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "description" in value;
  isInstance = isInstance && "dataset" in value;

  return isInstance;
}

export function FullExperimentDtoFromJSON(json: any): FullExperimentDto {
  return FullExperimentDtoFromJSONTyped(json, false);
}

export function FullExperimentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullExperimentDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    datasetId: json["datasetId"],
    name: json["name"],
    description: json["description"],
    dataset: FullDatasetDtoFromJSON(json["dataset"]),
  };
}

export function FullExperimentDtoToJSON(value?: FullExperimentDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    datasetId: value.datasetId,
    name: value.name,
    description: value.description,
    dataset: FullDatasetDtoToJSON(value.dataset),
  };
}
