/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and logs.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDatapointRunInput
 */
export interface UpdateDatapointRunInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateDatapointRunInput
     */
    datapointRunId: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateDatapointRunInput
     */
    output: object;
}

/**
 * Check if a given object implements the UpdateDatapointRunInput interface.
 */
export function instanceOfUpdateDatapointRunInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "datapointRunId" in value;
    isInstance = isInstance && "output" in value;

    return isInstance;
}

export function UpdateDatapointRunInputFromJSON(json: any): UpdateDatapointRunInput {
    return UpdateDatapointRunInputFromJSONTyped(json, false);
}

export function UpdateDatapointRunInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDatapointRunInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datapointRunId': json['datapointRunId'],
        'output': json['output'],
    };
}

export function UpdateDatapointRunInputToJSON(value?: UpdateDatapointRunInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datapointRunId': value.datapointRunId,
        'output': value.output,
    };
}

