/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ChangesDto
 */
export interface ChangesDto {
  /**
   *
   * @type {string}
   * @memberof ChangesDto
   */
  cost: string;
  /**
   *
   * @type {string}
   * @memberof ChangesDto
   */
  latency: string;
  /**
   *
   * @type {string}
   * @memberof ChangesDto
   */
  traces: string;
}

/**
 * Check if a given object implements the ChangesDto interface.
 */
export function instanceOfChangesDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "cost" in value;
  isInstance = isInstance && "latency" in value;
  isInstance = isInstance && "traces" in value;

  return isInstance;
}

export function ChangesDtoFromJSON(json: any): ChangesDto {
  return ChangesDtoFromJSONTyped(json, false);
}

export function ChangesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangesDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cost: json["cost"],
    latency: json["latency"],
    traces: json["traces"],
  };
}

export function ChangesDtoToJSON(value?: ChangesDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cost: value.cost,
    latency: value.latency,
    traces: value.traces,
  };
}
