/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnvInput
 */
export interface CreateEnvInput {
    /**
     * 
     * @type {string}
     * @memberof CreateEnvInput
     */
    name: string;
}

/**
 * Check if a given object implements the CreateEnvInput interface.
 */
export function instanceOfCreateEnvInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateEnvInputFromJSON(json: any): CreateEnvInput {
    return CreateEnvInputFromJSONTyped(json, false);
}

export function CreateEnvInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnvInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateEnvInputToJSON(value?: CreateEnvInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

