/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateProjectInput
 */
export interface CreateProjectInput {
  /**
   *
   * @type {string}
   * @memberof CreateProjectInput
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateProjectInput
   */
  orgId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateProjectInput
   */
  envNames: Array<string>;
}

/**
 * Check if a given object implements the CreateProjectInput interface.
 */
export function instanceOfCreateProjectInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "orgId" in value;
  isInstance = isInstance && "envNames" in value;

  return isInstance;
}

export function CreateProjectInputFromJSON(json: any): CreateProjectInput {
  return CreateProjectInputFromJSONTyped(json, false);
}

export function CreateProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    orgId: json["orgId"],
    envNames: json["envNames"],
  };
}

export function CreateProjectInputToJSON(value?: CreateProjectInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    orgId: value.orgId,
    envNames: value.envNames,
  };
}
