/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatapointRunDto
 */
export interface DatapointRunDto {
    /**
     * 
     * @type {string}
     * @memberof DatapointRunDto
     */
    id: string;
    /**
     * 
     * @type {object}
     * @memberof DatapointRunDto
     */
    output: object;
    /**
     * 
     * @type {string}
     * @memberof DatapointRunDto
     */
    experimentId: string;
    /**
     * 
     * @type {string}
     * @memberof DatapointRunDto
     */
    datapointId: string;
}

/**
 * Check if a given object implements the DatapointRunDto interface.
 */
export function instanceOfDatapointRunDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "output" in value;
    isInstance = isInstance && "experimentId" in value;
    isInstance = isInstance && "datapointId" in value;

    return isInstance;
}

export function DatapointRunDtoFromJSON(json: any): DatapointRunDto {
    return DatapointRunDtoFromJSONTyped(json, false);
}

export function DatapointRunDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatapointRunDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'output': json['output'],
        'experimentId': json['experimentId'],
        'datapointId': json['datapointId'],
    };
}

export function DatapointRunDtoToJSON(value?: DatapointRunDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'output': value.output,
        'experimentId': value.experimentId,
        'datapointId': value.datapointId,
    };
}

