/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExperimentDto } from './ExperimentDto';
import {
    ExperimentDtoFromJSON,
    ExperimentDtoFromJSONTyped,
    ExperimentDtoToJSON,
} from './ExperimentDto';

/**
 * 
 * @export
 * @interface DatapointRunWithExperimentDto
 */
export interface DatapointRunWithExperimentDto {
    /**
     * 
     * @type {string}
     * @memberof DatapointRunWithExperimentDto
     */
    id: string;
    /**
     * 
     * @type {object}
     * @memberof DatapointRunWithExperimentDto
     */
    output: object;
    /**
     * 
     * @type {string}
     * @memberof DatapointRunWithExperimentDto
     */
    experimentId: string;
    /**
     * 
     * @type {string}
     * @memberof DatapointRunWithExperimentDto
     */
    datapointId: string;
    /**
     * 
     * @type {ExperimentDto}
     * @memberof DatapointRunWithExperimentDto
     */
    experiment: ExperimentDto;
}

/**
 * Check if a given object implements the DatapointRunWithExperimentDto interface.
 */
export function instanceOfDatapointRunWithExperimentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "output" in value;
    isInstance = isInstance && "experimentId" in value;
    isInstance = isInstance && "datapointId" in value;
    isInstance = isInstance && "experiment" in value;

    return isInstance;
}

export function DatapointRunWithExperimentDtoFromJSON(json: any): DatapointRunWithExperimentDto {
    return DatapointRunWithExperimentDtoFromJSONTyped(json, false);
}

export function DatapointRunWithExperimentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatapointRunWithExperimentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'output': json['output'],
        'experimentId': json['experimentId'],
        'datapointId': json['datapointId'],
        'experiment': ExperimentDtoFromJSON(json['experiment']),
    };
}

export function DatapointRunWithExperimentDtoToJSON(value?: DatapointRunWithExperimentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'output': value.output,
        'experimentId': value.experimentId,
        'datapointId': value.datapointId,
        'experiment': ExperimentDtoToJSON(value.experiment),
    };
}

