/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DatapointRunDto } from './DatapointRunDto';
import {
    DatapointRunDtoFromJSON,
    DatapointRunDtoFromJSONTyped,
    DatapointRunDtoToJSON,
} from './DatapointRunDto';
import type { DatasetDto } from './DatasetDto';
import {
    DatasetDtoFromJSON,
    DatasetDtoFromJSONTyped,
    DatasetDtoToJSON,
} from './DatasetDto';

/**
 * 
 * @export
 * @interface FullExperimentDto
 */
export interface FullExperimentDto {
    /**
     * 
     * @type {string}
     * @memberof FullExperimentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FullExperimentDto
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof FullExperimentDto
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof FullExperimentDto
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof FullExperimentDto
     */
    createdAt: string;
    /**
     * 
     * @type {DatasetDto}
     * @memberof FullExperimentDto
     */
    dataset: DatasetDto;
    /**
     * 
     * @type {Array<DatapointRunDto>}
     * @memberof FullExperimentDto
     */
    datapointRuns: Array<DatapointRunDto>;
}

/**
 * Check if a given object implements the FullExperimentDto interface.
 */
export function instanceOfFullExperimentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "datasetId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "dataset" in value;
    isInstance = isInstance && "datapointRuns" in value;

    return isInstance;
}

export function FullExperimentDtoFromJSON(json: any): FullExperimentDto {
    return FullExperimentDtoFromJSONTyped(json, false);
}

export function FullExperimentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullExperimentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'datasetId': json['datasetId'],
        'name': json['name'],
        'description': json['description'],
        'createdAt': json['createdAt'],
        'dataset': DatasetDtoFromJSON(json['dataset']),
        'datapointRuns': ((json['datapointRuns'] as Array<any>).map(DatapointRunDtoFromJSON)),
    };
}

export function FullExperimentDtoToJSON(value?: FullExperimentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'datasetId': value.datasetId,
        'name': value.name,
        'description': value.description,
        'createdAt': value.createdAt,
        'dataset': DatasetDtoToJSON(value.dataset),
        'datapointRuns': ((value.datapointRuns as Array<any>).map(DatapointRunDtoToJSON)),
    };
}

