/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface MaxDto
 */
export interface MaxDto {
  /**
   *
   * @type {string}
   * @memberof MaxDto
   */
  cost: string;
  /**
   *
   * @type {string}
   * @memberof MaxDto
   */
  latency: string;
}

/**
 * Check if a given object implements the MaxDto interface.
 */
export function instanceOfMaxDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "cost" in value;
  isInstance = isInstance && "latency" in value;

  return isInstance;
}

export function MaxDtoFromJSON(json: any): MaxDto {
  return MaxDtoFromJSONTyped(json, false);
}

export function MaxDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaxDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cost: json["cost"],
    latency: json["latency"],
  };
}

export function MaxDtoToJSON(value?: MaxDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cost: value.cost,
    latency: value.latency,
  };
}
