/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FullExperimentDto } from './FullExperimentDto';
import {
    FullExperimentDtoFromJSON,
    FullExperimentDtoFromJSONTyped,
    FullExperimentDtoToJSON,
} from './FullExperimentDto';

/**
 * 
 * @export
 * @interface PaginatedFullExperimentDto
 */
export interface PaginatedFullExperimentDto {
    /**
     * 
     * @type {FullExperimentDto}
     * @memberof PaginatedFullExperimentDto
     */
    experiment: FullExperimentDto;
    /**
     * 
     * @type {number}
     * @memberof PaginatedFullExperimentDto
     */
    totalDatapointRuns: number;
}

/**
 * Check if a given object implements the PaginatedFullExperimentDto interface.
 */
export function instanceOfPaginatedFullExperimentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "experiment" in value;
    isInstance = isInstance && "totalDatapointRuns" in value;

    return isInstance;
}

export function PaginatedFullExperimentDtoFromJSON(json: any): PaginatedFullExperimentDto {
    return PaginatedFullExperimentDtoFromJSONTyped(json, false);
}

export function PaginatedFullExperimentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFullExperimentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experiment': FullExperimentDtoFromJSON(json['experiment']),
        'totalDatapointRuns': json['totalDatapointRuns'],
    };
}

export function PaginatedFullExperimentDtoToJSON(value?: PaginatedFullExperimentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experiment': FullExperimentDtoToJSON(value.experiment),
        'totalDatapointRuns': value.totalDatapointRuns,
    };
}

