/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExperimentDto } from './ExperimentDto';
import {
    ExperimentDtoFromJSON,
    ExperimentDtoFromJSONTyped,
    ExperimentDtoToJSON,
} from './ExperimentDto';

/**
 * 
 * @export
 * @interface PaginatedExperimentsDto
 */
export interface PaginatedExperimentsDto {
    /**
     * 
     * @type {Array<ExperimentDto>}
     * @memberof PaginatedExperimentsDto
     */
    experiments: Array<ExperimentDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedExperimentsDto
     */
    totalCount: number;
}

/**
 * Check if a given object implements the PaginatedExperimentsDto interface.
 */
export function instanceOfPaginatedExperimentsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "experiments" in value;
    isInstance = isInstance && "totalCount" in value;

    return isInstance;
}

export function PaginatedExperimentsDtoFromJSON(json: any): PaginatedExperimentsDto {
    return PaginatedExperimentsDtoFromJSONTyped(json, false);
}

export function PaginatedExperimentsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedExperimentsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experiments': ((json['experiments'] as Array<any>).map(ExperimentDtoFromJSON)),
        'totalCount': json['totalCount'],
    };
}

export function PaginatedExperimentsDtoToJSON(value?: PaginatedExperimentsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experiments': ((value.experiments as Array<any>).map(ExperimentDtoToJSON)),
        'totalCount': value.totalCount,
    };
}

