/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and logs.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDatapointRunInput
 */
export interface CreateDatapointRunInput {
    /**
     * 
     * @type {string}
     * @memberof CreateDatapointRunInput
     */
    experimentId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDatapointRunInput
     */
    datapointId: string;
}

/**
 * Check if a given object implements the CreateDatapointRunInput interface.
 */
export function instanceOfCreateDatapointRunInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "experimentId" in value;
    isInstance = isInstance && "datapointId" in value;

    return isInstance;
}

export function CreateDatapointRunInputFromJSON(json: any): CreateDatapointRunInput {
    return CreateDatapointRunInputFromJSONTyped(json, false);
}

export function CreateDatapointRunInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatapointRunInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experimentId': json['experimentId'],
        'datapointId': json['datapointId'],
    };
}

export function CreateDatapointRunInputToJSON(value?: CreateDatapointRunInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experimentId': value.experimentId,
        'datapointId': value.datapointId,
    };
}

