/* tslint:disable */
/* eslint-disable */
/**
 * Montelo API SDK
 * This server handles creating traces and logs.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExperimentWithDatapointsDto } from './ExperimentWithDatapointsDto';
import {
    ExperimentWithDatapointsDtoFromJSON,
    ExperimentWithDatapointsDtoFromJSONTyped,
    ExperimentWithDatapointsDtoToJSON,
} from './ExperimentWithDatapointsDto';

/**
 * 
 * @export
 * @interface PaginatedExperimentWithDatapointsDto
 */
export interface PaginatedExperimentWithDatapointsDto {
    /**
     * 
     * @type {ExperimentWithDatapointsDto}
     * @memberof PaginatedExperimentWithDatapointsDto
     */
    experiment: ExperimentWithDatapointsDto;
    /**
     * 
     * @type {number}
     * @memberof PaginatedExperimentWithDatapointsDto
     */
    totalDatapoints: number;
}

/**
 * Check if a given object implements the PaginatedExperimentWithDatapointsDto interface.
 */
export function instanceOfPaginatedExperimentWithDatapointsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "experiment" in value;
    isInstance = isInstance && "totalDatapoints" in value;

    return isInstance;
}

export function PaginatedExperimentWithDatapointsDtoFromJSON(json: any): PaginatedExperimentWithDatapointsDto {
    return PaginatedExperimentWithDatapointsDtoFromJSONTyped(json, false);
}

export function PaginatedExperimentWithDatapointsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedExperimentWithDatapointsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experiment': ExperimentWithDatapointsDtoFromJSON(json['experiment']),
        'totalDatapoints': json['totalDatapoints'],
    };
}

export function PaginatedExperimentWithDatapointsDtoToJSON(value?: PaginatedExperimentWithDatapointsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experiment': ExperimentWithDatapointsDtoToJSON(value.experiment),
        'totalDatapoints': value.totalDatapoints,
    };
}

