name: Deploy UI

on:
  push:
    branches:
      - main
    paths:
      - "apps/ui/**"
      - "packages/browser-client/**"

jobs:
  deploy:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy UI
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_UI }}
        working-directory: ./apps/ui
      - name: Post to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "C06MVSMSKRV"
          slack-message: "UI Deploy Status: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
