name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/db/**"

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
        working-directory: ./apps/api

  slack-notification:
    name: Post to Slack channel
    id: slack
    uses: slackapi/slack-github-action@v1.25.0
    with:
      channel-id: "C06MVSMSKRV"
      slack-message: "API Deploy Status: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
