name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/db/**"

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
        working-directory: ./apps/api
